### ISSUE TITLE
Readme - SONNAME instead of JSONNAME

### ISSUE THREAD

**Issue by eduard93** [SeanConnelly/Cogs#1]
Readme contains:
`Property DateOfBirth As %Date(SONNAME="BirthDate");`
It should be JSONNAME.

**Comment by SeanConnelly** [comment]
Thanks, fixed!

**Comment by eduard93** [comment]
Also Storeing -> Storing in https://github.com/SeanConnelly/Cogs/blob/master/docs/JsonClass.md

**Comment by SeanConnelly** [comment]
Excellent, thanks.
