### ISSUE TITLE
Depth limiting or output-once strategy

### ISSUE THREAD

**Issue by eduard93** [SeanConnelly/Cogs#2]
Consider the following two classes:
```
Class Cogs.Test.Parent Extends (%Persistent, Cogs.JsonClass)
{

Property Child As Child;

/// do ##class(Cogs.Test.Parent).Test()
ClassMethod Test()
{
	do ..%KillExtent()
	do ##class(Cogs.Test.Child).%KillExtent()
	
	set obj = ..%New()
	do obj.ChildSetObjectId(1)
	w obj.%Save(),!
	
	set child = ##class(Cogs.Test.Child).%New()
	do child.ParentSetObjectId(1)
	w child.%Save(),!
	
	kill
	
	set obj = ..%OpenId(1)
	w obj.toJSON()
}
}
```
and:
```
Class Cogs.Test.Child Extends (%Persistent, Cogs.JsonClass)
{

Property Parent As Parent;
}
```

Calling `do ##class(Cogs.Test.Parent).Test()` causes <FRAMESTACK> error. Limiting traversal depth or implementing output-once strategy can solve this problem.
[XML with classes](https://gist.githubusercontent.com/eduard93/913d6215576a09f56cfc2ac10ed7d5be/raw/87fe713bf27c404872b90cdad536885bdbd3f84d/cogstest.xml).

**Comment by SeanConnelly** [comment]
Good call.
I have upgraded Cogs.Lib.Json.ClassSerializer to track objects seen at the child level. It will stop deep recursion, whilst allowing multiple references at the same parent level as this might be needed.
