### ISSUE TITLE
Use $zcvt in Cogs.Lib.Json.Base:EscapeJSON

### ISSUE THREAD

**Issue by eduard93** [SeanConnelly/Cogs#3]
I think $zcvt would be faster:
`$zcvt(string","O","JSON")`
for older versions (before 2015.2), without JSON translate table, current method can be used as a fallback.

**Comment by SeanConnelly** [comment]
Another good call, this was something I was going to look into but forgot.
A quick benchmark shows it is 7x faster, will help shave a bit of time off the overall serialization time.
Will make an enhancement...

**Comment by SeanConnelly** [comment]
Have upgraded the class to conditional bake $zcvt into the code, latest version is cogs.jsonclass.1.0.2.xml
