### ISSUE TITLE
Parsing fails on specific message construct

### ISSUE THREAD

**Issue by stefanc82** [SeanConnelly/Cogs#4]
A message with the following layout fails parsing:
{
	"MandateListDto": [{
		"Id": "40444019-fb52-40bd-82fa-be3d51a90ac8",
		"Name": "TestDebtor",
		"CreationDateUtc": "2017-07-15T08:25:59.6670000Z",
		"MandateStatus": {
			"Status": "Rejected",
			"AuthenticationDate": "2017-07-15T00:00:00.0000000Z",
			"MandateBankReferenceNumber": "",
			"RejectReasons": [""]
		}
	}],
	"PageIndex": 1,
	"PageSize": 1,
	"ErrorList": [],
	"ResponseUtcTime": "2017-07-16T10:28:42.8798267Z",
	"UserFriendlyDisplayList": []
}

It tries to parse the PageIndex property into the  MandateStatus object.

I resolved this by inserting this line prior to "if "}]"[pre continue"
if ("}"=c),(ctype="") g END

**Comment by SeanConnelly** [comment]
Hi,
The problem occurs when the last property of an object is a list.
You fix works for your particular instance, but it breaks other unit tests.
I've tested this change...

if "}]"[pre continue

to

if ((pre="}")||(pre="]")&&(c'="}")) continue

which works for your instance and all other unit tests.

I will write some more unit tests around this scenario and will push a new release sometime today.

Thanks for logging the issue.
Sean.

**Comment by stefanc82** [comment]
Hi Sean,

Thank you.

Regards,
[STEFAN CRONJE]<https://gov.qlink.co.za/QLHome/terms_conditions.php>

**Comment by SeanConnelly** [comment]
Fixed.
